name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'zhayujie/chatgpt-on-wechat' # 上游仓库
          ref: 'master' # 分支名

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/upstream-repo-owner/upstream-repo.git
          git fetch upstream
          git checkout main
          git rebase upstream/main

      - name: Push changes
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
